services:
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - notifications-data:/app/data  # Persistent storage
    environment:
      - CONTAINERS=1 # Permite listar y ver info de contenedores
      - IMAGES=1     # Permite listar imágenes
      - POST=1       # Permite hacer pull de imágenes
    networks:
      - docker-internal

  image-checker:
    image: difagume/image-checker:1.0.1
    container_name: image-checker
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=http://docker-proxy:2375
      - TZ=America/Guayaquil
    depends_on:
      - docker-proxy
    networks:
      - docker-internal

networks:
  docker-internal:
    driver: bridge
