allowBuilds:
  cpu-features: true
  msw: true
  protobufjs: true
  sharp: true
  ssh2: true
minimumReleaseAgeExclude:
  - '@number-flow/react@0.6.2'
  - number-flow@0.6.2
  - shadcn@4.16.1
overrides:
  postcss@8.4.31: '^8.5.19'
  sharp@^0.34.5: '^0.35.3'
