import type { ContainerInfo, ImageInfo } from 'dockerode'
import { checkImageUpdate } from '@/actions/docker'
import { getDictionary, type Locale } from '@/lib/i18n/dictionaries'
import { getReferenceUrls } from '@/lib/reference-url-manager'
import type {
	ContainerUpdate,
	NotificationMessage
} from '@/types/notifications'
import { getEnabledProviders } from './provider-factory'
import {
	getPreferredLanguage,
	hasBeenNotified,
	loadState,
	markAsNotified
} from './state-manager'

/**
 * Check for container updates and send notifications
 */
export async function checkAndNotify(
	containers: ContainerInfo[],
	images: ImageInfo[]
): Promise<void> {
	console.log('▶️ Starting notification check...')

	const providers = getEnabledProviders()

	if (providers.length === 0) {
		console.log('🚫 No notification providers enabled, skipping notifications')
		return
	}

	console.log(
		`🔔 Active notification providers: ${providers.map((p) => p.name).join(', ')}`
	)

	const state = await loadState()
	const ignoredNotificationIds = state.ignoredNotificationIds || []
	const referenceUrls = await getReferenceUrls()
	const updates: ContainerUpdate[] = []

	// Check each container for updates
	for (const container of containers) {
		try {
			const containerName = container.Names?.[0]?.replace('/', '') || 'Unnamed'

			// Skip ignored containers
			if (ignoredNotificationIds.includes(container.Id)) {
				console.log(
					`🔕 Container ${containerName} has notifications disabled, skipping notification`
				)
				continue
			}

			// Find local image details
			const localImage = images.find((img) => img.Id === container.ImageID)
			let localDigest = localImage?.RepoDigests?.[0]?.split('@')[1]

			// Fallback to ImageID if no repo digest
			if (!localDigest && container.ImageID) {
				localDigest = container.ImageID
			}

			// Check for updates
			const updateInfo = await checkImageUpdate(container.Image, localDigest)

			// Skip if no update available or if it's a local image
			if (!updateInfo.hasUpdate || updateInfo.isLocal) {
				continue
			}

			// Skip if no latest digest (can't track properly)
			if (!updateInfo.latestDigest) {
				continue
			}

			// Extract image name without tag and current tag
			const imageParts = container.Image.split(':')
			const imageNameOnly = imageParts[0] // e.g., "anoniemerd/prunemate"
			const currentTag = imageParts[1] || 'latest' // e.g., "latest"

			// Determine current version: prefer updateInfo.currentVersion, fallback to tag
			const currentVersion =
				updateInfo.currentVersion && updateInfo.currentVersion !== 'Unknown'
					? updateInfo.currentVersion
					: currentTag

			const update: ContainerUpdate = {
				containerId: '', // Will be generated by state manager
				containerName,
				imageName: imageNameOnly, // Only image name, no tag
				imageDigest: localDigest || '',
				currentVersion, // Actual version or tag
				latestVersion: updateInfo.latestVersion || 'latest',
				latestDigest: updateInfo.latestDigest,
				dockerHubUrl: updateInfo.dockerHubUrl,
				lastUpdated: updateInfo.lastUpdated
			}

			// Check if already notified
			if (hasBeenNotified(state, update)) {
				console.log(`⏭️ Update for ${containerName} already notified, skipping`)
				continue
			}

			updates.push(update)
		} catch (error) {
			console.error(
				`❌ Error checking container ${container.Names?.[0]}:`,
				error
			)
		}
	}

	// Send notifications for new updates
	if (updates.length === 0) {
		console.log('📭 No new updates to notify')
		return
	}

	console.log(`📣 Found ${updates.length} new update(s) to notify`)

	// Get preferred language and dictionary
	const language = (await getPreferredLanguage()) as Locale
	const dict = getDictionary(language)
	const t = dict.notifications

	for (const update of updates) {
		const message: NotificationMessage = {
			containerName: update.containerName,
			imageName: update.imageName, // Already without tag
			currentVersion: update.currentVersion, // Already resolved
			latestVersion: update.latestVersion,
			dockerHubUrl: update.dockerHubUrl,
			referenceUrl: referenceUrls[update.imageName]?.referenceUrl,
			lastUpdated: update.lastUpdated,
			translations: {
				title: t.title,
				container: t.container,
				image: t.image,
				current: t.current,
				latest: t.latest,
				updated: t.updated,
				viewReference: t.viewReference
			},
			locale: language
		}

		// Send to all providers
		const results = await Promise.allSettled(
			providers.map((provider) => provider.send(message))
		)

		// Log results
		results.forEach((result, index) => {
			if (result.status === 'fulfilled') {
				console.log(`✅ Notification sent via ${providers[index].name}`)
			} else {
				console.error(
					`❌ Failed to send via ${providers[index].name}:`,
					result.reason
				)
			}
		})

		// Mark as notified even if some providers failed
		// (to avoid spam if one provider is temporarily down)
		await markAsNotified(update)
	}

	console.log('🏁 Notification check completed')
}
